version: '3.9'

services:
  postgres-poupy:
    container_name: postgres-poupy
    image: postgres:16.1-alpine
    ports:
      - "5433:5433"
    volumes:
      - /data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - PGPORT=5433

  django-poupy:
    container_name: django-poupy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8000"
    volumes:
      - ./project:/project
    env_file:
      - .env
    depends_on:
      - postgres-poupy