services:
  database:
    container_name: db-poupy
    image: postgres:16.1-alpine
    ports:
      - "5434:5434"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - PGPORT=5434
    restart: always

  app:
    container_name: app-poupy
    image: poupy:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8000"
    volumes:
      - ./project:/project
    env_file:
      - .env
    depends_on:
      - database
    restart: always

volumes:
  pgdata: