# Generated by Django 5.0 on 2023-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='type',
            field=models.CharField(default='TRANSFER', max_length=8),
        ),
    ]
