# Generated by Django 4.2.7 on 2023-11-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_remove_income_account_delete_expanse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Receita'), ('TRANSFERÊNCIA', 'Transferência')], default='DESPESA', max_length=20),
        ),
    ]
