# Generated by Django 5.0 on 2023-12-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transfer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transaction_date',
        ),
    ]
