# Generated by Django 4.2.7 on 2023-11-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('TRANSFER', 'Transferência')], default='EXPENSE', max_length=8),
        ),
    ]
